[SC-533] memory-safe-assembly
1inch/limit-order-protocol pull request #119
Opened 2022-06-23 21:21 UTC by zZoMROT

2022-06-24 16:09 UTC, k06a commented
Not all assembly blocks were covered within this PR :(

2022-06-27 12:38 UTC, ZumZoom requested changes

2022-06-27 12:38 UTC, ZumZoom commented on contracts/libraries/ArgumentsDecoder.sol
>              value := mload(add(data, 0x20))
This is unsafe, since we don't know whether `data + 0x20` was allocated until we check that data has sufficient length.

2022-06-27 12:38 UTC, ZumZoom commented on contracts/libraries/ArgumentsDecoder.sol
>              value := eq(mload(add(data, 0x20)), 1)
This is unsafe, since we don't know whether `data + 0x20` was allocated until we check that data has sufficient length.

2022-07-04 06:51 UTC, ZumZoom approved these changes

2022-07-04 06:57 UTC, ZumZoom commented
> * `deployedBytecode` decreased
>   
>   * from `28330` to `28308` for `LimitOrderProtocol`
>   * from `21328` to `21320` for `LimitOrderProtocolPro`
> 
> <img alt="Снимок экрана 2022-07-03 в 11 43 43" width="1263" src="https://user-images.githubusercontent.com/3616087/177032415-5384c6ad-954d-4fe4-804f-85073ca29d90.png">
> 
> * gas spent has changed as follows:
> 
> <img alt="Снимок экрана 2022-07-03 в 11 43 30" width="1263" src="https://user-images.githubusercontent.com/3616087/177032401-a7d38650-6bb5-4aa8-9d00-ae3eb19ee620.png">

This gas usage decrease was caused by solidity-utils upgrade

2022-07-04 06:58 UTC, merged