[SC-765] Combine ETH orders mappings into one
1inch/limit-order-protocol pull request #227
Opened 2023-03-03 14:25 UTC by typicalbuster

2023-03-03 14:31 UTC, k06a requested changes

2023-03-03 14:31 UTC, k06a commented on contracts/helpers/ETHOrders.sol
> +    mapping(bytes32 => uint256) private _ordersMakersBalances;
Let’s use struct with address and uint96, code will be cleaner

2023-03-03 14:31 UTC, k06a commented
Let’s also have one getter returning two arrays

2023-03-03 17:02 UTC, k06a commented on contracts/helpers/ETHOrders.sol
> -    function ethOrderBalances(bytes32[] calldata orderHashes) external view returns(uint256[] memory rawAmounts) {
Please make multi-getter, returning `ETHOrder[]`

2023-03-03 17:03 UTC, k06a commented on contracts/helpers/ETHOrders.sol
> +        ordersMakersBalances[orderHash] = ETHOrder(msg.sender, uint96(msg.value));
```suggestion
        ordersMakersBalances[orderHash] = ETHOrder({
            maker: msg.sender,
            balance: uint96(msg.value)
        });
```

2023-03-03 17:04 UTC, k06a commented on contracts/helpers/ETHOrders.sol
> +     * @notice Sets _ordersMakersBalances to 0, refunds ETH and does standard order cancellation on Limit Order Protocol.
```suggestion
     * @notice Sets `ordersMakersBalances` to 0, refunds ETH and does standard order cancellation on Limit Order Protocol.
```

2023-03-06 06:14 UTC, ZumZoom approved these changes

2023-03-06 06:14 UTC, merged