chore(SC-940): Move extensions to separate folder
1inch/limit-order-protocol pull request #278
Opened 2023-10-12 10:38 UTC by artall64

2023-10-12 15:12 UTC, byshape approved these changes

2023-10-12 17:22 UTC, zZoMROT commented on contracts/extensions/DutchAuctionCalculator.sol
> +/// @title A helper that implement price decay over time from max to min
```suggestion
/// @title A helper that implements price decay over time from max to min
```

2023-10-12 17:23 UTC, zZoMROT commented on contracts/extensions/DutchAuctionCalculator.sol
> +/// @notice This contact is used in 1inch Fusion orders
```suggestion
/// @notice This contract is used in 1inch Fusion orders
```

2023-10-12 17:24 UTC, zZoMROT commented on contracts/extensions/ETHOrders.sol
> +/// @title Extension that will allow to create limit order that sell ETH. ETH would need to be deposited to contract
```suggestion
/// @title Extension that will allow to create limit order that sell ETH. ETH must be deposited into the contract
```

2023-10-12 17:26 UTC, zZoMROT approved these changes

2023-10-13 03:01 UTC, galekseev requested changes
Please, consider suggested description changes.
Perhaps, it makes sense to move OrderLib to libraries folder (discussible).

2023-10-13 03:01 UTC, galekseev commented on contracts/extensions/DutchAuctionCalculator.sol
> +/// @title A helper that implement price decay over time from max to min
```suggestion
/// @title The helper implements price decay over time from max to min
```

2023-10-13 03:01 UTC, galekseev commented on contracts/extensions/DutchAuctionCalculator.sol
> +/// @notice This contact is used in 1inch Fusion orders
```suggestion
/// @notice The contact implements Dutch auction price calculation for 1inch limit orders
```

2023-10-13 03:01 UTC, galekseev commented on contracts/extensions/ETHOrders.sol
> +/// @title Extension that will allow to create limit order that sell ETH. ETH would need to be deposited to contract
```suggestion
/// @title The extension for 1inch Limit Order protocol to sell ETH. ETH must  be deposited to the contract.
```

2023-10-13 03:01 UTC, galekseev commented on contracts/extensions/WethUnwrapper.sol
> +/// @title A contract that can be called within postPredicate to unwrap WETH and do payout in ETH
```suggestion
/// @title The extension to unwrap WETH and do payout in ETH in limit order postInteraction
```

2023-10-13 03:01 UTC, galekseev commented on contracts/extensions/WethUnwrapper.sol
> +/// @notice This functionality was embedded into TakerTraits, so this file probably will be removed
```suggestion
/// @notice The feature was embedded into TakerTraits, so it is obsolete and will be removed
```

2023-10-13 03:01 UTC, galekseev commented on contracts/libraries/AmountCalculatorLib.sol
> +/// @title A helper library for calculations related to order amounts
```suggestion
/// @title The helper library to calculate linearly taker amount from maker amount and vice versa.
```

2023-10-13 10:24 UTC, artall64 commented
@zZoMROT @galekseev pls check out lates changes on comments

2023-10-13 19:36 UTC, galekseev approved these changes

2023-10-16 11:21 UTC, merged