chore(SC-940): move extensions to separate folder and cleanup
1inch/limit-order-protocol pull request #284
Opened 2023-10-19 10:34 UTC by artall64

- Dropped WethUnwrapper
- Dropped NonceManager and fix naming in tests
- Move ChainLink calculator to extenstions

2023-10-19 15:51 UTC, ZumZoom requested changes

2023-10-19 15:51 UTC, ZumZoom commented on test/SeriesNonceManager.js
Rename the file as well to the `SeriesEpochManager.js`

2023-10-19 15:51 UTC, ZumZoom commented on contracts/helpers/SeriesNonceManager.sol
This file is still needed for legacy reasons. To exclude it from coverage you'll need to update the `skipFiles` sections of `.solcover.js`.

2023-10-19 15:51 UTC, ZumZoom commented on deploy/deploy-helpers.js
This changes are irrelevant as the `SeriesEpochManager` is inherited in the `OrderMixin` so there is no need to deploy it separately. However the `SeriesNonceManager` is needed for legacy reasons, and it is deployed separately hence the need of the deploy script.

2023-10-20 12:37 UTC, artall64 commented on contracts/helpers/SeriesNonceManager.sol
done

2023-10-20 12:37 UTC, artall64 commented on test/SeriesNonceManager.js
done

2023-10-20 12:38 UTC, artall64 commented on deploy/deploy-helpers.js
done

2023-10-20 12:44 UTC, ZumZoom approved these changes

2023-10-20 12:45 UTC, merged