Updated the protocol description (in description.md)
1inch/limit-order-protocol pull request #285
Opened 2023-10-25 21:15 UTC by galekseev

* Updated description of fill functions using args calldata
* Updated natspecs for TakerTraits

2023-10-26 08:59 UTC, ZumZoom requested changes

2023-10-26 08:59 UTC, ZumZoom commented on description.md
> +
```suggestion
```

2023-10-31 19:50 UTC, byshape approved these changes

2023-11-07 07:49 UTC, ZumZoom approved these changes

2023-11-07 07:49 UTC, merged